export enum OrderStatus {
  PENDING = "PENDING",
  CLICKING_BUTTONS = "CLICKING_BUTTONS",
  ENTERING_INFO = "ENTERING_INFO",
  REQUESTING_PAYMENT = "REQUESTING_PAYMENT",
  WAITING_FOR_PAYMENT = "WAITING_FOR_PAYMENT",
  DONE = "DONE",
}
