name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      # Disabled for now due to the long time it takes
      # - name: Deploy to unRaid server
      #   run: bash ./scripts/updateLatestDockerOnUnraid.bash
      #   env:
      #     UNRAID_HTTP_USERNAME: ${{ secrets.UNRAID_HTTP_USERNAME }}
      #     UNRAID_HTTP_PASSWORD: ${{ secrets.UNRAID_HTTP_PASSWORD }}
      #     UNRAID_USERNAME: ${{ secrets.UNRAID_USERNAME }}
      #     UNRAID_PASSWORD: ${{ secrets.UNRAID_PASSWORD }}
